// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGol4pGkUOp_JpCnxFwu2vAVYCFLUY9sE',
    appId: '1:684070545463:web:5282cea13d84b6933f77b2',
    messagingSenderId: '684070545463',
    projectId: 'college-project-25e9e',
    authDomain: 'college-project-25e9e.firebaseapp.com',
    storageBucket: 'college-project-25e9e.firebasestorage.app',
    measurementId: 'G-ZF0WNBH9P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVE1lQvrvAgVsqxd9L74U4g_rdYj_Eho',
    appId: '1:684070545463:android:44b81c7934a1259b3f77b2',
    messagingSenderId: '684070545463',
    projectId: 'college-project-25e9e',
    storageBucket: 'college-project-25e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LNq9wWgqTJPgh_PJfe8fMVndfzIjOHU',
    appId: '1:684070545463:ios:8252f0272d21c8e53f77b2',
    messagingSenderId: '684070545463',
    projectId: 'college-project-25e9e',
    storageBucket: 'college-project-25e9e.firebasestorage.app',
    iosBundleId: 'com.clg.event.clgEventManagementNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LNq9wWgqTJPgh_PJfe8fMVndfzIjOHU',
    appId: '1:684070545463:ios:8252f0272d21c8e53f77b2',
    messagingSenderId: '684070545463',
    projectId: 'college-project-25e9e',
    storageBucket: 'college-project-25e9e.firebasestorage.app',
    iosBundleId: 'com.clg.event.clgEventManagementNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGol4pGkUOp_JpCnxFwu2vAVYCFLUY9sE',
    appId: '1:684070545463:web:d64074161f0b592b3f77b2',
    messagingSenderId: '684070545463',
    projectId: 'college-project-25e9e',
    authDomain: 'college-project-25e9e.firebaseapp.com',
    storageBucket: 'college-project-25e9e.firebasestorage.app',
    measurementId: 'G-NMPPL26DXQ',
  );
}
